export const locations = [
  { value: 'Abia', label: 'Abia' },
  { value: 'Adamawa', label: 'Adamawa' },
  { value: 'Akwa Ibom', label: 'Akwa Ibom' },
  { value: 'Anambra', label: 'Anambra' },
  { value: 'Bauchi', label: 'Bauchi' },
  { value: 'Bayelsa', label: 'Bayelsa' },
  { value: 'Benue', label: 'Benue' },
  { value: 'Borno', label: 'Borno' },
  { value: 'Cross River', label: 'Cross River' },
  { value: 'Delta', label: 'Delta' },
  { value: 'Ebonyi', label: 'Ebonyi' },
  { value: 'Edo', label: 'Edo' },
  { value: 'Ekiti', label: 'Ekiti' },
  { value: 'Enugu', label: 'Enugu' },
  { value: 'Gombe', label: 'Gombe' },
  { value: 'Imo', label: 'Imo' },
  { value: 'Jigawa', label: 'Jigawa' },
  { value: 'Kaduna', label: 'Kaduna' },
  { value: 'Kano', label: 'Kano' },
  { value: 'Katsina', label: 'Katsina' },
  { value: 'Kebbi', label: 'Kebbi' },
  { value: 'Kogi', label: 'Kogi' },
  { value: 'Kwara', label: 'Kwara' },
  { value: 'Lagos', label: 'Lagos' },
  { value: 'Nasarawa', label: 'Nasarawa' },
  { value: 'Niger', label: 'Niger' },
  { value: 'Ogun', label: 'Ogun' },
  { value: 'Ondo', label: 'Ondo' },
  { value: 'Osun', label: 'Osun' },
  { value: 'Oyo', label: 'Oyo' },
  { value: 'Plateau', label: 'Plateau' },
  { value: 'Rivers', label: 'Rivers' },
  { value: 'Sokoto', label: 'Sokoto' },
  { value: 'Taraba', label: 'Taraba' },
  { value: 'Yobe', label: 'Yobe' },
  { value: 'Zamfara', label: 'Zamfara' },
  { value: 'FCT', label: 'FCT' },

  
];

export const propertyTypes = [
  { value: 'Any', label: 'Any' },
  { value: 'Self Contain', label: 'Self Contain' },
  { value: 'Mini Flats', label: 'Mini Flats' },
  { value: 'Flats/Apartments', label: 'Flat/Apartments' },
  { value: 'Semi Detached Bungalow', label: 'Semi Detached Bungalow' },
  { value: 'Detached Bungalow', label: 'Detached Bungalow' },
  { value: 'Semi Detached Duplex', label: 'Semi Detached Duplex' },
  { value: 'Detached Duplex', label: 'Detached Duplex' },
  { value: 'Terraced Duplex', label: 'Terraced Duplex' },
];

export const prices = [
  { value: '< ₦200,000', label: '< ₦200,000' },
  { value: '₦200,000 - ₦400,000', label: '₦200,000 - ₦400,000' },
  { value: '₦400,000 - ₦600,000', label: '₦400,000 - ₦600,000' },
  { value: '₦600,000 - ₦800,000', label: '₦600,000 - ₦800,000' },
  { value: '₦800,000 - ₦1,000,000', label: '₦800,000 - ₦1,000,000' },
  { value: '₦1,000,000 - ₦1,200,000', label: '₦1,000,000 - ₦1,200,000' },
  { value: '₦1,200,000 - ₦1,400,000', label: '₦1,200,000 - ₦1,400,000' },
  { value: '₦1,400,000 - ₦1,600,000', label: '₦1,400,000 - ₦1,600,000' },
  { value: '₦1,600,000 - ₦2,000,000', label: '₦1,600,000 - ₦2,000,000' },
  { value: '₦2,000,000 - ₦5,000,000', label: '₦2,000,000 - ₦5,000,000' },

];

export const bedrooms = [
  { value: '1', label: '1' },
  { value: '2', label: '2' },
  { value: '3', label: '3' },
  { value: '4', label: '4' },
  { value: '5', label: '5' },
];