export const locations = [
  { value: 'Abia', label: 'Abia' },
  { value: 'Adamawa', label: 'Adamawa' },
  { value: 'Akwa Ibom', label: 'Akwa Ibom' },
  { value: 'Anambra', label: 'Anambra' },
  { value: 'Bauchi', label: 'Bauchi' },
  { value: 'Bayelsa', label: 'Bayelsa' },
  { value: 'Benue', label: 'Benue' },

  //   "Bauchi",
  //   "Benue",
  //   "Borno",
  //   "Bayelsa",
  //   "Cross River",
  //   "Delta",
  //   "Ebonyi",
  //   "Edo",
  //   "Ekiti",
  //   "Enugu",
  //   "Federal Capital Territory",
  //   "Gombe",
  //   "Imo",
  //   "Jigawa",
  //   "Kebbi",
  //   "Kaduna",
  //   "Kano",
  //   "Kogi",
  //  "Katsina",
  //  "Kwara",
  //  "Lagos",
  //   "Nasarawa",
  //   "Niger",
  //   "Ogun",
  //   "Ondo",
  //  "Osun",
  //    "Oyo",
  //   "Plateau",
  //   "Rivers",
  //    "Sokoto",
  //  "Taraba",
  //  "Yobe",
  //  "Zamfara",
];

export const propertyTypes = [
  { value: 'Apartment', label: 'Apartment' },
  { value: 'House', label: 'House' },
  { value: 'Villa', label: 'Villa' },
  { value: 'Flat', label: 'Flat' },
  { value: 'Shop', label: 'Shop' },
  { value: 'Office', label: 'Office' },
  { value: 'Land', label: 'Land' },
  { value: 'Warehouse', label: 'Warehouse' },
];
